version: '3'
services:
  mongo:
    image: 'mongo'
    restart: always
    environment:
       MONGO_INITDB_ROOT_USERNAME: 'root'
       MONGO_INITDB_ROOT_PASSWORD: 'example'
  docker-app:
    build: ./
    ports:
      - "5000:5000"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'example'
      NODE_ENV: 'docker'
      PORT: '5000'